language: ruby
rvm:
  - 2.2.5
env:
  - USE_SYSTEM_GECODE=1
before_install:
  - sudo apt-get update
  - sudo apt-get install libgecode-dev
install:
  - bundle install --path vendor --binstubs
script:
  - bin/berks install
  - bin/rake style
