name 'amazon-ecs-agent'
maintainer 'Will Salt'
maintainer_email 'williamejsalt@gmail.com'
source_url 'https://github.com/willejs/chef-amazon-ecs-agent'
issues_url 'https://github.com/willejs/chef-amazon-ecs-agent/issues'
license 'Apache 2.0'
description 'Installs/Configures amazon-ecs-agent'
long_description 'Installs/Configures amazon-ecs-agent'
version '2.0.1'

supports 'ubuntu'

depends 'chef-apt-docker', '~> 1.0'
depends 'chef-sugar'
depends 'docker', '~> 2.9'
depends 'iptables', '~> 3.0'
depends 'sysctl', '~> 0.7'
